volumes:
  db_data:

services:
  db:
    image: postgres:15.5-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - app.default.env
    ports:
      - '5432:5432'

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: menulance-be/app
    entrypoint: /entrypoints/wait_for_db.sh
    volumes:
      - ./src/menulance:/code
      - ./data:/var/www/data/
    depends_on:
      - db
    env_file:
      - app.default.env
    environment:
      SERVICE_ID: api
      ON_DOCKER: 1
    ports:
      - '8000:8000'

