volumes:
  db_data:

services:
  db:
    image: postgres:15.5-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - app.default.env
    ports:
      - '5432:5432'

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: menulance/backend
    entrypoint: /entrypoints/wait_for_db.sh
    command:
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/menulance:/code
      - ./data:/var/www/data/
    depends_on:
      - db
    env_file:
      - app.default.env
    environment:
      SERVICE_ID: api
      ON_DOCKER: 1
    ports:
      - '8000:8000'

  admin:
    image: menulance/backend
    entrypoint: /entrypoints/wait_for_db.sh
    command:
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/menulance:/code
      - ./data:/var/www/data/
    depends_on:
      - db
    env_file:
      - app.default.env
    environment:
      SERVICE_ID: admin
      ON_DOCKER: 1
    ports:
      - '8001:8000'

  notebook:
    image: menulance/backend
    command: [ "python3", "manage.py", "shell_plus", "--notebook" ]
    volumes:
      - ./backend/src:/code
      - ./data:/var/www/data/
    depends_on:
      - db
    env_file:
      - app.default.env
    environment:
      SERVICE_ID: notebook
      DJANGO_ALLOW_ASYNC_UNSAFE: 1
      ALLOW_ROOT: 1
