# Generated by Django 4.2.9 on 2024-02-03 12:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Entity created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entity updated at"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only these special characters are allowed: ,.'-",
                                regex="^[a-zA-Z,.'-]*$",
                            )
                        ],
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only these special characters are allowed: ,.'-",
                                regex="^[a-zA-Z,.'-]*$",
                            )
                        ],
                        verbose_name="Last name",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
