# Generated by Django 4.2.9 on 2024-02-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactformentry",
            options={
                "verbose_name": "ContactFormEntry",
                "verbose_name_plural": "ContactFormEntries",
            },
        ),
        migrations.RemoveField(
            model_name="contactformentry",
            name="created_by",
        ),
        migrations.AddField(
            model_name="contactformentry",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
    ]
