# Generated by Django 4.2.9 on 2024-02-03 20:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only these special characters are allowed: ,.'-",
                        regex="^[a-zA-Z,.'-]*$",
                    )
                ],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only these special characters are allowed: ,.'-",
                        regex="^[a-zA-Z,.'-]*$",
                    )
                ],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Entity updated at"
            ),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(
                        help_text="Specify the preferred font size.",
                        null=True,
                        verbose_name="Font Size",
                    ),
                ),
                (
                    "enable_wizard",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable or disable the user interface wizard.",
                        verbose_name="Enable Wizard",
                    ),
                ),
                (
                    "enable_pro_tips",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to display or hide pro tips in the user interface.",
                        verbose_name="Enable Pro Tips",
                    ),
                ),
                (
                    "enable_autodetect",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable or disable auto detection feature.",
                        verbose_name="Enable Autodetect",
                    ),
                ),
                (
                    "enable_soundfx",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable or disable sound effects in the application.",
                        verbose_name="Enable Sound Effects",
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to display or hide notifications.",
                        verbose_name="Enable Notifications",
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        help_text="Select the preferred font.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.font",
                        verbose_name="Preferred Font",
                    ),
                ),
                (
                    "ui_language",
                    models.ForeignKey(
                        help_text="Choose the preferred language for the user interface.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="UI Language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserPreference",
                "verbose_name_plural": "UserPreferences",
            },
        ),
    ]
