# Generated by Django 4.2.9 on 2024-02-03 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreferences",
            old_name="user",
            new_name="creator",
        ),
    ]
