# Generated by Django 4.2.9 on 2024-02-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="font",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="language",
            name="short_code",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="manuallytranslatedword",
            name="from_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_translations_from",
                to="core.language",
            ),
        ),
        migrations.AlterField(
            model_name="manuallytranslatedword",
            name="original_word",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuallytranslatedword",
            name="to_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_translations_to",
                to="core.language",
            ),
        ),
        migrations.AlterField(
            model_name="manuallytranslatedword",
            name="translated_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="manuallytranslatedword",
            unique_together={
                ("original_word", "from_language", "to_language", "created_by")
            },
        ),
    ]
