# Generated by Django 4.2.9 on 2024-02-05 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_font_name_alter_language_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="font",
            options={"verbose_name": "Font", "verbose_name_plural": "Fonts"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="manuallytranslatedword",
            options={
                "verbose_name": "ManuallyTranslatedWord",
                "verbose_name_plural": "ManuallyTranslatedWord",
            },
        ),
        migrations.RenameField(
            model_name="manuallytranslatedword",
            old_name="created_by",
            new_name="creator",
        ),
        migrations.AlterUniqueTogether(
            name="manuallytranslatedword",
            unique_together={
                ("original_word", "from_language", "to_language", "creator")
            },
        ),
    ]
